[![AnalyticsDojo](https://github.com/rpi-techfundamentals/spring2019-materials/blob/master/fig/final-logo.png?raw=1)](http://rpi.analyticsdojo.com)
<center><h1>Introduction to R - Datastructures</h1></center>
<center><h3><a href = "http://rpi.analyticsdojo.com">rpi.analyticsdojo.com</a></h3></center>



# Overview
Common to R and Python
- Vectors
- Opearations on Numeric and String Variables
- Lists




## Vectors in R
- The most basic form of an R object is a vector. 
- In fact, individual (scalar) values (variables) are vectors of length one.
- An R vector is a single set of values in a particular order of the **same type**. 
- We can concatenate values into a vector with c(): `ages<-c(18,19,18,23)`
- Comparable Python objects include Panda Series and single dimensional numpy array. 
- While Python arrays start at 0, R arrays start at index position 1. 

In [1]:

ages<-c(18,19,18,23)
ages
ages[1]
ages[2:4]



[1] 18 19 18 23

[1] 18

[1] 19 18 23

## Vectors Type in R
- Items in a vector must be of the same type. 
- *Character.* These are the clear character vectors. (Typically use quotes to add to these vectors.)
- *Numeric.* Numbers in a set. Note there is not a different type.
- *Boolean.* TRUE or FALSE values in a set.
- *Factor.* A situation in which there is a select set of options. Things such as states or zip codes. These are typically things which are related to dummy variables, a topic we will discuss later.
- Determine the data type by using the `str` command: `str(teachers)`

In [2]:
names<-c("Sally", "Jason", "Bob", "Susy") #Text
female<-c(TRUE, FALSE, FALSE, TRUE)  #While Python uses True and False, R uses TRUE and FALSE.
teachers<-c("Smith", "Johnson", "Johnson", "Smith")
teachers.f<-factor(teachers)
grades<-c(20, 15, 13, 19) #25 points possible
gradesdec<-c(20.32, 15.32, 13.12, 19.32) #25 points possible

str(names)
str(female)
str(teachers)  
str(teachers.f) 
str(grades)    #Note that the grades and gradesdec are both numeric.
str(gradesdec) #Note that the grades and gradesdec are both numeric.


 chr [1:4] "Sally" "Jason" "Bob" "Susy"
 logi [1:4] TRUE FALSE FALSE TRUE
 chr [1:4] "Smith" "Johnson" "Johnson" "Smith"
 Factor w/ 2 levels "Johnson","Smith": 2 1 1 2
 num [1:4] 20 15 13 19
 num [1:4] 20.3 15.3 13.1 19.3


## Strings in R
- Lot's of different types of operations we can perform on Strings. 

In [6]:
chars <- c('hi', 'hallo', "mother's", 'father\'s', "He said, \'hi\'" )
length(chars)
nchar(chars)
paste("bill", "clinton", sep = " ")  # paste together a set of strings
paste(chars, collapse = ' ')  # paste together things from a vector

strlist<-strsplit("This is the Analytics Dojo", split = " ") #This taks a string ant splits to a list
strlist
substring(chars, 2, 3) #this takes the 2nd-3rd character from the sentance above 
chars2 <- chars
substring(chars2, 2, 3) <- "ZZ"  #this takes the 2nd-3rd character from the sentance above 
chars2

[1] 5

[1]  2  5  8  8 13

[1] "bill clinton"

[1] "hi hallo mother's father's He said, 'hi'"

[[1]]
[1] "This"      "is"        "the"       "Analytics" "Dojo"

[1] "i"  "al" "ot" "at" "e "

[1] "hZ"            "hZZlo"         "mZZher's"      "fZZher's"     
[5] "HZZsaid, 'hi'"

## Factors in R 
- A factor is a special data type in R used for categorical data. In some cases it works like magic and in others it is incredibly frustrating.



In [7]:
class(teachers.f) # What order are the factors in?
levels(teachers.f)  # note alternate way to get the variable
summary(teachers.f) #gives the count for each level. 


[1] "factor"

[1] "Johnson" "Smith"

Johnson   Smith 
      2       2

## Creating Vectors in R
- Concatenate fields to a vector: `nums <- c(1.1, 3, -5.7)`
- Generate random values from normal distribution with `devs <- rnorm(5)`
- idevs <- sample(ints, 100, replace = TRUE)


In [8]:
# numeric vector
nums <- c(1.1, 3, -5.7)
devs <- rnorm(5)
devs

# integer vector
ints <- c(1L, 5L, -3L) # force storage as integer not decimal number
# "L" is for "long integer" (historical)

idevs <- sample(ints, 100, replace = TRUE)

# character vector
chars <- c("hi", "hallo", "mother's", "father\'s", 
   "She said", "hi", "He said, \'hi\'" )
chars
cat(chars, sep = "\n")

# logical vector
bools <- c(TRUE, FALSE, TRUE)
bools

[1]  0.6204789  0.3557198 -0.4824207  1.9607785 -1.2218590

[1] "hi"            "hallo"         "mother's"      "father's"     
[5] "She said"      "hi"            "He said, 'hi'"

hi
hallo
mother's
father's
She said
hi
He said, 'hi'


[1]  TRUE FALSE  TRUE

## Variable Type 
- In R when we write `b = 30` this means the value of `30` is assigned to the `b` object. 
- R is a [dynamically typed](https://pythonconquerstheuniverse.wordpress.com/2009/10/03/static-vs-dynamic-typing-of-programming-languages/).
- Unlike some languages, we don"t have to declare the type of a variable before using it. 
- Variable type can also change with the reassignment of a variable. 
- We can query the class a value using the `class` function.
- The `str` function gives additional details for complex objects like dataframes.



In [9]:
a <- 1L
print (c("The value of a is ", a))
print (c("The value of a is ", a), quote=FALSE)
class(a)
str(a)

a <- 2.5
print (c("Now the value of a is ", a),quote=FALSE)
class(a)
str(a)

a <- "hello there"
print (c("Now the value of a is ", a ),quote=FALSE)
class(a)
str(a)

[1] "The value of a is " "1"                 
[1] The value of a is  1                 


[1] "integer"

 int 1
[1] Now the value of a is  2.5                   


[1] "numeric"

 num 2.5
[1] Now the value of a is  hello there           


[1] "character"

 chr "hello there"


## Converting Values Between Types

- We can convert values between different types.
- To convert to string use the `as.character` function.
- To convert to numeric use the `as.integer` function.
- To convert to an integer use the `as.integer` function.
- To convert to a boolean use the `as.logical` function.


In [10]:
#This is a way of specifying a long integer.
a <- 1L
a
class(a)
str(a)
a<-as.character(a)
a
class(a)
str(a)
a<-as.numeric(a)
a
class(a)
str(a)
a<-as.logical(a)
a
class(a)
str(a)


[1] 1

[1] "integer"

 int 1


[1] "1"

[1] "character"

 chr "1"


[1] 1

[1] "numeric"

 num 1


[1] TRUE

[1] "logical"

 logi TRUE


## Quotes 
- Double Quotes are preferred in R, though both will work as long as they aren't mixed. 

In [11]:
#Double Quotes are preferred in R, though both will work as long as they aren't mixed. 
a <- "hello"
class(a)
str(a)
a <- 'hello'
class(a)
str(a)

[1] "character"

 chr "hello"


[1] "character"

 chr "hello"


# Null Values

- Since it was designed by statisticians, R handles missing values very well relative to other languages.
- `NA` is a missing value


In [12]:
#Notice nothing is printed.
a<-NA
a
vec <- rnorm(12)    #This creates a vector with randomly distributed values
vec[c(3, 5)] <- NA  #This sets values 3 and 5 as NA
vec                 #This prints the Vector
sum(vec)            #What is the Sum of a vector that has NA?  
sum(vec, na.rm = TRUE)   #This Sums the vector with the NA removed. 
is.na(vec)          #This returns a vector of whether specific values are equal to NA.

[1] NA

[1] -1.3364455  1.8742115         NA -0.2173462         NA  0.4357703
 [7] -1.1402553 -0.4834595 -0.9002826 -0.6186187  1.0470747 -1.5078951

[1] NA

[1] -2.847246

[1] FALSE FALSE  TRUE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE

## Logical/Boolean Vectors
- Here we can see that summing and averaging boolean vectors treats `TRUE=1 & FALSE=0`

In [13]:
answers <- c(TRUE, TRUE, FALSE, FALSE)
update <- c(TRUE, FALSE, TRUE, FALSE)

# Here we see that True coul
sum(answers)
mean(answers)
total<-answers + update
total
class(total)

[1] 2

[1] 0.5

[1] 2 1 1 0

[1] "integer"

## R Calculations
- R can act as a basic calculator.

In [9]:
2 + 2 # add numbers
2 * pi # multiply by a constant
7 + runif(1) # add a random number
3^4 # powers
sqrt(4^4) # functions
log(10)
log(100, base = 10)
23 %/% 2 
23 %% 2

# scientific notation
5000000000 * 1000
5e9 * 1e3

[1] 4

[1] 6.283185

[1] 7.38707

[1] 81

[1] 16

[1] 2.302585

[1] 2

[1] 11

[1] 1

[1] 5e+12

[1] 5e+12

## Operations on Vectors
- R can be used as a basic calculator.
- We can do calculations on vectors easily. 
- Direct operations are much faster easier than looping.


In [11]:
#vals <- rnorm(10)
#squared2vals <- vals^2
#sum_squared2vals <- sum(chi2vals)
#ount_squared2vals<-length(squared2vals)  
#vals
#squared2vals
#sum_df1000
#count_squared2vals


## R is a Functional Language

- Operations are carried out with functions. Functions take objects as inputs and return objects as outputs. 
- An analysis can be considered a pipeline of function calls, with output from a function used later in a subsequent operation as input to another function.
- Functions themselves are objects. 
- We can get help on functions with help(lm) or ?lm

In [14]:
vals <- rnorm(10)
median(vals)
class(median)
median(vals, na.rm = TRUE)
mean(vals, na.rm = TRUE)
help(lm)
?lm
?log



[1] 0.6445466

[1] "function"

[1] 0.6445466

[1] 0.6315396

lm                    package:stats                    R Documentation

_F_i_t_t_i_n_g _L_i_n_e_a_r _M_o_d_e_l_s

_D_e_s_c_r_i_p_t_i_o_n:

     ‘lm’ is used to fit linear models.  It can be used to carry out
     regression, single stratum analysis of variance and analysis of
     covariance (although ‘aov’ may provide a more convenient interface
     for these).

_U_s_a_g_e:

     lm(formula, data, subset, weights, na.action,
        method = "qr", model = TRUE, x = FALSE, y = FALSE, qr = TRUE,
        singular.ok = TRUE, contrasts = NULL, offset, ...)
     
_A_r_g_u_m_e_n_t_s:

 formula: an object of class ‘"formula"’ (or one that can be coerced to
          that class): a symbolic description of the model to be
          fitted.  The details of model specification are given under
          ‘Details’.

    data: an optional data frame, list or environment (or object
          coercible by ‘as.data.frame’ to a data frame) containing the
          variables in the model.  If not found in ‘data’, the
          variables are taken from ‘environment(formula)’, typically
          the environment from which ‘lm’ is called.

  subset: an optional vector specifying a subset of observations to be
          used in the fitting process.

 weights: an optional vector of weights to be used in the fitting
          process.  Should be ‘NULL’ or a numeric vector.  If non-NULL,
          weighted least squares is used with weights ‘weights’ (that
          is, minimizing ‘sum(w*e^2)’); otherwise ordinary least
          squares is used.  See also ‘Details’,

na.action: a function which indicates what should happen when the data
          contain ‘NA’s.  The default is set by the ‘na.action’ setting
          of ‘options’, and is ‘na.fail’ if that is unset.  The
          ‘factory-fresh’ default is ‘na.omit’.  Another possible value
          is ‘NULL’, no action.  Value ‘na.exclude’ can be useful.

  method: the method to be used; for fitting, currently only ‘method =
          "qr"’ is supported; ‘method = "model.frame"’ returns the
          model frame (the same as with ‘model = TRUE’, see below).

model, x, y, qr: logicals.  If ‘TRUE’ the corresponding components of
          the fit (the model frame, the model matrix, the response, the
          QR decomposition) are returned.

singular.ok: logical. If ‘FALSE’ (the default in S but not in R) a
          singular fit is an error.

contrasts: an optional list. See the ‘contrasts.arg’ of
          ‘model.matrix.default’.

  offset: this can be used to specify an _a priori_ known component to
          be included in the linear predictor during fitting.  This
          should be ‘NULL’ or a numeric vector of length equal to the
          number of cases.  One or more ‘offset’ terms can be included
          in the formula instead or as well, and if more than one are
          specified their sum is used.  See ‘model.offset’.

     ...: additional arguments to be passed to the low level regression
          fitting functions (see below).

_D_e_t_a_i_l_s:

     Models for ‘lm’ are specified symbolically.  A typical model has
     the form ‘response ~ terms’ where ‘response’ is the (numeric)
     response vector and ‘terms’ is a series of terms which specifies a
     linear predictor for ‘response’.  A terms specification of the
     form ‘first + second’ indicates all the terms in ‘first’ together
     with all the terms in ‘second’ with duplicates removed.  A
     specification of the form ‘first:second’ indicates the set of
     terms obtained by taking the interactions of all terms in ‘first’
     with all terms in ‘second’.  The specification ‘first*second’
     indicates the _cross_ of ‘first’ and ‘second’.  This is the same
     as ‘first + second + first:second’.

     If the formula includes an ‘offset’, this is evaluated and
     subtracted from the response.

     If ‘response’ is a matrix a linear model is fitted separately by
   

## Matrix 
- Multiple column vector
- Matrix is useful for linear algebra
- Matrix must be **all of the same type**
- Could relatively easily do regression calculations using undlerlying matrix

In [12]:
#This is setup a matrix(vector, nrow,ncol)
mat <- matrix(rnorm(12), nrow = 3, ncol = 4)
mat
# This is setup a matrix(vector, rows)
A <- matrix(1:12, 3)
B <- matrix(1:12, 4)
C <- matrix(seq(4,36, by = 4), 3)
A
B
C

[,1]        [,2]       [,3]      [,4]
[1,] -0.8352688  0.06464287  0.3968016 0.8912246
[2,]  2.0589154 -0.44420685  0.4423272 0.1642597
[3,]  1.3309925 -2.32858882 -1.8560133 2.0487820

[,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

[,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12

[,1] [,2] [,3]
[1,]    4   16   28
[2,]    8   20   32
[3,]   12   24   36

## Slicing Vectors and Matrixs
- Can use matrix[rows,columns] with specificating of row/column index, name, range. 


In [15]:
vec <- rnorm(12)
mat <- matrix(vec, 4, 3)
rownames(mat) <- letters[1:4] #This assigns a row name
vec
mat



[1]  0.23584710 -1.22658917 -1.18402684  1.50615065 -0.20618211 -0.41235588
 [7] -0.07999345 -1.72561819  0.76499317  1.25314418 -1.12655890 -2.45245615

[,1]       [,2]        [,3]      
a  0.2358471 -0.20618211  0.7649932
b -1.2265892 -0.41235588  1.2531442
c -1.1840268 -0.07999345 -1.1265589
d  1.5061506 -1.72561819 -2.4524562

In [16]:
#Slicing Vector
vec[c(3, 5, 8:10)] # This gives position 3, 5, and 8-10

[1] -1.1840268 -0.2061821 -1.7256182  0.7649932  1.2531442

In [17]:
# matrix[rows,columns]  leaving blank means all columns/rows
mat[c('a', 'd'), ]
mat[c(1,4), ]
mat[c(1,4), 1:2]
mat[c(1,4), c(1,3)] #Notice when providing a list we surround with c
mat[, 1:2]          #When providing a range we use a colon.

[,1]      [,2]       [,3]      
a 0.2358471 -0.2061821  0.7649932
d 1.5061506 -1.7256182 -2.4524562

[,1]      [,2]       [,3]      
a 0.2358471 -0.2061821  0.7649932
d 1.5061506 -1.7256182 -2.4524562

[,1]      [,2]      
a 0.2358471 -0.2061821
d 1.5061506 -1.7256182

[,1]      [,2]      
a 0.2358471  0.7649932
d 1.5061506 -2.4524562

[,1]       [,2]       
a  0.2358471 -0.20618211
b -1.2265892 -0.41235588
c -1.1840268 -0.07999345
d  1.5061506 -1.72561819

## Lists
- Collections of disparate or complicated objects.
- Can be of multiple different types. 
- Here we assign individual values with the list with `=`.
- Slice the list with the index position or the name. 

In [13]:
#myList <- list(stuff = 3, mat = matrix(1:4, nrow = 2), moreStuff = c('china', 'japan'), list(5, 'bear'))
myList<-list(stuff=3,mat = matrix(1:4, nrow = 2),vector=c(1,2,3,4),morestuff=c("Albany","New York", "San Francisco"))
myList

#
myList['stuff']
myList[2]
myList[2:3]
myList[c(1,4)]


$stuff
[1] 3

$mat
     [,1] [,2]
[1,]    1    3
[2,]    2    4

$vector
[1] 1 2 3 4

$morestuff
[1] "Albany"        "New York"      "San Francisco"

$stuff
[1] 3

$mat
     [,1] [,2]
[1,]    1    3
[2,]    2    4

$mat
     [,1] [,2]
[1,]    1    3
[2,]    2    4

$vector
[1] 1 2 3 4

$stuff
[1] 3

$morestuff
[1] "Albany"        "New York"      "San Francisco"

## CREDITS

Copyright [AnalyticsDojo](http://rpi.analyticsdojo.com) 2016
This work is licensed under the [Creative Commons Attribution 4.0 International](https://creativecommons.org/licenses/by/4.0/) license agreement.

Adopted from the [Berkley R Bootcamp](https://github.com/berkeley-scf/r-bootcamp-2016).

